/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSuperAdminRouteImport } from './routes/_layout/super-admin'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutPlayerAnalyticsRouteImport } from './routes/_layout/player-analytics'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutInsightsRouteImport } from './routes/_layout/insights'
import { Route as LayoutFantasyStatsRouteImport } from './routes/_layout/fantasy-stats'
import { Route as LayoutBlogRouteImport } from './routes/_layout/blog'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutBlogPostIdRouteImport } from './routes/_layout/blog.$postId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSuperAdminRoute = LayoutSuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPlayerAnalyticsRoute = LayoutPlayerAnalyticsRouteImport.update({
  id: '/player-analytics',
  path: '/player-analytics',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutInsightsRoute = LayoutInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFantasyStatsRoute = LayoutFantasyStatsRouteImport.update({
  id: '/fantasy-stats',
  path: '/fantasy-stats',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBlogRoute = LayoutBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBlogPostIdRoute = LayoutBlogPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => LayoutBlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/blog': typeof LayoutBlogRouteWithChildren
  '/fantasy-stats': typeof LayoutFantasyStatsRoute
  '/insights': typeof LayoutInsightsRoute
  '/items': typeof LayoutItemsRoute
  '/player-analytics': typeof LayoutPlayerAnalyticsRoute
  '/settings': typeof LayoutSettingsRoute
  '/super-admin': typeof LayoutSuperAdminRoute
  '/blog/$postId': typeof LayoutBlogPostIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/blog': typeof LayoutBlogRouteWithChildren
  '/fantasy-stats': typeof LayoutFantasyStatsRoute
  '/insights': typeof LayoutInsightsRoute
  '/items': typeof LayoutItemsRoute
  '/player-analytics': typeof LayoutPlayerAnalyticsRoute
  '/settings': typeof LayoutSettingsRoute
  '/super-admin': typeof LayoutSuperAdminRoute
  '/': typeof LayoutIndexRoute
  '/blog/$postId': typeof LayoutBlogPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/blog': typeof LayoutBlogRouteWithChildren
  '/_layout/fantasy-stats': typeof LayoutFantasyStatsRoute
  '/_layout/insights': typeof LayoutInsightsRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/player-analytics': typeof LayoutPlayerAnalyticsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/super-admin': typeof LayoutSuperAdminRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/blog/$postId': typeof LayoutBlogPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/blog'
    | '/fantasy-stats'
    | '/insights'
    | '/items'
    | '/player-analytics'
    | '/settings'
    | '/super-admin'
    | '/blog/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/blog'
    | '/fantasy-stats'
    | '/insights'
    | '/items'
    | '/player-analytics'
    | '/settings'
    | '/super-admin'
    | '/'
    | '/blog/$postId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/blog'
    | '/_layout/fantasy-stats'
    | '/_layout/insights'
    | '/_layout/items'
    | '/_layout/player-analytics'
    | '/_layout/settings'
    | '/_layout/super-admin'
    | '/_layout/'
    | '/_layout/blog/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/super-admin': {
      id: '/_layout/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof LayoutSuperAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/player-analytics': {
      id: '/_layout/player-analytics'
      path: '/player-analytics'
      fullPath: '/player-analytics'
      preLoaderRoute: typeof LayoutPlayerAnalyticsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/insights': {
      id: '/_layout/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof LayoutInsightsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/fantasy-stats': {
      id: '/_layout/fantasy-stats'
      path: '/fantasy-stats'
      fullPath: '/fantasy-stats'
      preLoaderRoute: typeof LayoutFantasyStatsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/blog': {
      id: '/_layout/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof LayoutBlogRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/blog/$postId': {
      id: '/_layout/blog/$postId'
      path: '/$postId'
      fullPath: '/blog/$postId'
      preLoaderRoute: typeof LayoutBlogPostIdRouteImport
      parentRoute: typeof LayoutBlogRoute
    }
  }
}

interface LayoutBlogRouteChildren {
  LayoutBlogPostIdRoute: typeof LayoutBlogPostIdRoute
}

const LayoutBlogRouteChildren: LayoutBlogRouteChildren = {
  LayoutBlogPostIdRoute: LayoutBlogPostIdRoute,
}

const LayoutBlogRouteWithChildren = LayoutBlogRoute._addFileChildren(
  LayoutBlogRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutBlogRoute: typeof LayoutBlogRouteWithChildren
  LayoutFantasyStatsRoute: typeof LayoutFantasyStatsRoute
  LayoutInsightsRoute: typeof LayoutInsightsRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutPlayerAnalyticsRoute: typeof LayoutPlayerAnalyticsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutSuperAdminRoute: typeof LayoutSuperAdminRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutBlogRoute: LayoutBlogRouteWithChildren,
  LayoutFantasyStatsRoute: LayoutFantasyStatsRoute,
  LayoutInsightsRoute: LayoutInsightsRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutPlayerAnalyticsRoute: LayoutPlayerAnalyticsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutSuperAdminRoute: LayoutSuperAdminRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
